import './globals.css';
import type { Metadata } from 'next';
import { Barlow, Fraunces } from 'next/font/google';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const barlowFontFamily = Barlow({
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
  variable: '--font-barlow',
  fallback: ['sans-serif'],
  subsets: ['latin'],
});

const frauncesFontFamily = Fraunces({
  weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
  variable: '--font-fraunces',
  fallback: ['serif'],
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang='en'
      className={`${barlowFontFamily.variable} ${frauncesFontFamily.variable}`}
    >
      <body>
        <main>{children}</main>
      </body>
    </html>
  );
}
